### ISSUE TITLE
NameError: name 'cc' is not defined

### ISSUE THREAD

**Issue by mstc-xqp** [3huo/3DV-Action#6]
S001C001P001R001A001
Traceback (most recent call last):
  File "ntu120_3dv_pre.py", line 240, in <module>
    main()
  File "ntu120_3dv_pre.py", line 149, in main
    points_xyzc = np.concatenate((xyz,cc.T), axis = 1)  #final 3DV point feature shape N*(x,y,z,m_g,m_1,...m_t)
NameError: name 'cc' is not defined

Hi! I found that there is no cc

**Comment by 3huo** [comment]
Thanks for your kindly comments. The 'cc' should be 'motion'
